version: '3'

services:
  weatherapp_backend:
    depends_on:
      - weatherapp_proxy
    build: ./backend
    ports: 
      - "9000:9000"
    container_name: weatherapp_backend
    environment:
      - APPID=YOUR_WEATHER_API_ID_TOKEN
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - TARGET_CITY=Helsinki,fi
    restart: always

  weatherapp_frontend:
    depends_on:
      - weatherapp_proxy
    build: 
      context: ./frontend
      args:
      - ENDPOINT=api
      - PORT=8000
    ports: 
      - "8000:8000"
    container_name: weatherapp_frontend
    links:
      - weatherapp_backend
    restart: always

  weatherapp_proxy:
    build: ./proxy
    ports: 
      - "80:80"
    container_name: weatherapp_proxy
    restart: always