version: '3'

services:
  weatherapp_backend:
    build: ./backend
    ports: 
      - "9000:9000"
    container_name: weatherapp_backend
  weatherapp_frontend:
    build: ./frontend
    ports: 
      - "80:80"
    container_name: weatherapp_frontend
    links:
    - weatherapp_backend
    tty: true
